Responsified layout for small screens
wiomoc/geimpft pull request #1
Opened 2021-01-11 00:24 UTC by r2binx

Moves the map component below the charts to make it accessible on small screens and the sidebar fills the whole width. Maybe needs a little more refinement. Perhaps it would be good to restrict the height of the map in order to scroll on a touchscreen.
For now I added a FAB to scroll back to the top.

2021-01-11 00:32 UTC, wiomoc requested changes

2021-01-11 00:32 UTC, wiomoc commented on app/src/components/ScrollTopButton.vue
> +@import url("https://fonts.googleapis.com/css?family=Material+Icons");
Manual import
see arrow_back in toolbar

2021-01-11 00:32 UTC, wiomoc commented on app/src/components/ScrollTopButton.vue
> +@import url("https://fonts.googleapis.com/css?family=Material+Icons");
the rest LGTM

2021-01-12 12:35 UTC, r2binx commented on app/src/components/Sidebar.vue
> +  z-index: 1000;
Not sure why such a high value is necessary. Shouldn't be the case.

2021-01-12 13:20 UTC, merged